# Generated by Django 5.0.7 on 2025-04-27 22:19

import teams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="access_code",
            field=models.CharField(
                default=teams.models.generate_unique_code, max_length=8, unique=True
            ),
        ),
    ]
