# Generated by Django 5.0.7 on 2025-04-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cravings", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cravinglog",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cravinglog",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
